### PR TITLE
change sandbox SECRET_KEY

### PR DESCRIPTION
**Pull request by jedie**

### CODE REVIEW

**Comment by mj026** [comment]
Why would the existing secret key be a problem?

**Comment by jedie** [comment]
It's not really a problem. The old value, which looks like a correct "secret" value, appears to have been committed accidentally ;)

**Comment by mj026** [comment]
The key is auto generated when bootstrapping a django project so there is no problem here, thanks for noticing!

**Comment by jedie** [comment]
> The key is auto generated when bootstrapping a django project so there is no problem here, thanks for noticing!

Yeah, I got that. But that is not the point.

I think if someone sees the source code, they wonder about that. And maybe he think that this may a mistake ;)

**Pull request closed without merging**
