### PR TITLE
All my updates...

### PR DESCRIPTION
**Pull request by jedie**
Sorry, no time to create clean, separate pull requests... Here are just all my "develop" branch changes...

### CODE REVIEW

**Comment by mj026** [comment]
I won't be merging this pull request as it is a bit messy as you stated. I'll be happy to pick the commits and clean the commit messages if you want, just let me know.

**Comment by jedie** [comment]
Of course you can pick commits. As written, I don't have time to do that in single pull requests, sorry.

This pull request is only a "public" overview of all changes.

**Comment by mj026** [comment]
I'll cherry pick commits here and there so you can leave the pull request open for now

**Comment by jedie** [comment]
Look in my opened issued: i usually specified which commit is the fix for each issue ;)

**Comment by mj026** [comment]
I think I picked all relevant commits from this pull request now. Could you close it and add new pull requests for new features based on the master branch from now on?

**Pull request closed without merging**
