### PR TITLE
Added facade and interface unittests, custom DocdataMockTransport responses with set_responses

### PR DESCRIPTION
**Pull request by mj026**

### CODE REVIEW

**Comment by jedie** [comment]
Great that you will implement some really needed tests ;)

What's about to implement it in a way that other can use the mockups in own project integration tests?

**Comment by mj026** [comment]
The test fixtures and the suds transport you mean? Can you specify what would be useful for reuse?

**Comment by jedie** [comment]
I mean everything needed to run own payment integrations tests. I copied this data into my project:

- `mock_suds_client()` and `mock_transport()` from `tests/conftest.py`
- `tests/testdata/docdata_responses.py`
- `tests/testdata/wsdl-1_3.wsdl`
- `tests/testdata/xsd1-1_3.xsd`

I can imagine that for others the pytest fixtures are also interesting. But I have my own.

Maybe it would be easiest to move the complete tests into the package. Probably into: `/oscar_docdata/tests/`

**Comment by mj026** [comment]
I tried moving some of the test utility code inside the package, but most of it is dependent on `pytest`. Which means I would have to make `pytest` a dependency, otherwise I'll ship code without proper dependency management. So I'll stick with this setup for now.

**Pull request merged**
