### PR TITLE
Raise error if order.status is unknown

### PR DESCRIPTION
**Pull request by jedie**

### CODE REVIEW

**Comment by mj026** [comment]
I'm not  really keen on the `RuntimeError` exception here, nor that  a unknown status can occur.

**Comment by jedie** [comment]
Yeah, that's never supposed to happen.
But maybe they are thinking about introducing a new status however.
That's the general way I do it. I think it's better to count on the unexpected ;)

**Comment by mj026** [comment]
I disagree on the part to write code to count on the unexpected. When an unexpected result comes it should break. 

And this sandbox application is, as I stated before, not meant to be a full blown working application but a starting point for your own project so there is no need to add a lot of safety nets here.

**Comment by vdboor** [comment]
Perhaps `logger.warning(...)` instead? Or `raise NotImplementedError(...)`?

**Comment by mj026** [comment]
`logger.warning` would make sense, so if you add that I'll merge it

**Comment by jedie** [comment]
I don't think a warning would be enough. That might quickly be overlooked, as you sayed:

> When an unexpected result comes it should break.

...and a warning will not break.

> And this sandbox application is [...] a starting point for your own project so there is no need to add a lot of safety nets here.

IMHO the starting point should be a good template ;)

**Comment by mj026** [comment]
> ...and a warning will not break.

You are right. Can you change it to raise the [DocdataStatusException](https://github.com/django-oscar/django-oscar-docdata/blob/master/oscar_docdata/exceptions.py#L38) ?

**Comment by jedie** [comment]
done

**Pull request merged**
